### PR TITLE
Beta 1 Part 4

### LINKED ISSUE #132: 6-text messages display all six messages
This is original behavior but the Display Message nodes I created afterward did not acknowledge the saving of the space for 6 texts.

---
This is an item logged from the To-Do and was originally reported by Tados. If you are familiar with or can recreate this bug, please provide details here.

### LINKED ISSUE #685: Some editor dialogs are missing a cancel button
This is possibly a comprehensive list of them… unless there are subdialogs that also have the issue.

* [ ] Scenario Details
* [ ] Advanced Scenario Details
* [ ] Set Variable Town Entry
* [ ] Set Scenario Event Timers
* [ ] Set Town Event Timers
* [ ] Town Details
* [ ] Town Wandering Monsters
* [ ] Outdoor Details

### LINKED ISSUE #703: Resurrection balm feature flag
I think we once talked about resurrection balm not being a feature of the legacy game? If the ingredients for it can't be found in legacy scenarios/designers weren't balancing around it at the time, I think the requirement of resurrection balm (and ppossibly the inclusion of its recipe in the menu) should be a scenario feafure flag.

The spell description would also change.

### LINKED ISSUE #707: scons doesn't repackage modified core scenarios

### LINKED ISSUE #729: Launch from scenario editor: can't find Blades of Exile on Mac
On Mac, if I launch the scenario editor by directly double-clicking the `.app` bundle, the working directory seems to be somewhere in the bundle (maybe `Contents/MacOS`? but it doesn't really matter). When I try to launch a scenario using the launch buttons, it can't find `Blades of Exile.app` because it expects it to be in the working directory.

I think we had talked about a fallback where it lets you specify an explicit path. That might be good, but in this case, on Mac it should search at the directory containing the bundle folder.

### LINKED ISSUE #733: Blade wall hard to see against cave floor
Here in ZKR is the first time I've seen the Blade Wall field while playtesting.

Image

GitHub is enlarging the image a bit from actual size. At first, I thought there was a bug and the blade walls were invisible.

### LINKED ISSUE #735: Conveyor belts push big monsters through 1-wide corridor
This affects legacy BoE as well. Efreets in ZKR are getting pushed through corridors that are not 2 tiles tall. The legs inhabit a blocked tile.

### LINKED ISSUE #736: Conveyors don't animate in combat.
This affects legacy BoE too.

### LINKED ISSUE #737: Sucking slimes will Gaze at PCs with 0 energy or 0 max energy
Sucking slimes aren't a very big threat on their own (see Pit of Plentiful Goo in ASR) because they're preferring to drain PCs over make damaging attacks, even when all casters are fully drained. They will also gaze at non-caster PCs whose max SP is 0.

I'm guessing this is a legacy bug, and would change balance.

### LINKED ISSUE #740: Misc UI bugs (MacOS)
Image

Default 2:1 UI scale is too large for the Preferences pane to fit. Selecting different UI scale doesn't immediately fix it. I guessed that I could press ENTER to save the settings and apply the scale. Might be safer to start the game UI at 1:1 scale on first load. Or add a scrollbar to Preferences pane if possible

Image

Issue with overlapping popup text lines when clicking on load party button

Image

Save party screen shows same overlapping popup text lines as above. It also shows a placeholder party for the autosave slot. Confused me at first

### LINKED ISSUE #741: Valley of Dying Things node error
Image

Attached file is a savegame just next to the error node. Just walk west after loading the save

### LINKED ISSUE #744: Scenario Editor - crash when loading a scenario
<details>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               BoE Scenario Editor [27482]
Path:                  /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/MacOS/BoE Scenario Editor
Identifier:            com.spidweb.boesceneditor
Version:               1.0
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-05-23 21:52:53.1858 +0200
OS Version:            macOS 15.3.1 (24D70)
Report Version:        12
Anonymous UUID:        31A2DAB3-D64B-CB2D-70A3-0F6A5FA40472

Sleep/Wake UUID:       E9AB18A3-2790-450B-B025-572E897EF705

Time Awake Since Boot: 130000 seconds
Time Since Wake:       46976 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000a7
Exception Codes:       0x0000000000000001, 0x00000000000000a7

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [27482]

VM Region Info: 0xa7 is not in any region.  Bytes before following region: 4333420377
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1024ac000-102b68000    [ 6896K] r-x/r-x SM=COW  /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/MacOS/BoE Scenario Editor

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   BoE Scenario Editor           	       0x1024ed050 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:ue170006]() const + 24
1   BoE Scenario Editor           	       0x1024ede60 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__get_pointer[abi:ue170006]() const + 28
2   BoE Scenario Editor           	       0x1024edcf0 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::data[abi:ue170006]() const + 24
3   BoE Scenario Editor           	       0x1024c1234 std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::operator<<[abi:ue170006]<char, std::__1::char_traits<char>, std::__1::allocator<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 36
4   BoE Scenario Editor           	       0x1024c0c7c set_up_main_screen() + 1276
5   BoE Scenario Editor           	       0x102720d64 set_current_out(location, bool, bool) + 184
6   BoE Scenario Editor           	       0x1024c5068 restore_editor_state(bool) + 88
7   BoE Scenario Editor           	       0x1024bace8 handle_lb_action(int) + 608
8   BoE Scenario Editor           	       0x1024b0f1c handle_lb_click(location) + 156
9   BoE Scenario Editor           	       0x1024b0c44 handle_action(location, sf::Event) + 236
10  BoE Scenario Editor           	       0x1026bcd24 Mouse_Pressed(sf::Event const&) + 112
11  BoE Scenario Editor           	       0x1026bca00 handle_one_event(sf::Event const&) + 308
12  BoE Scenario Editor           	       0x1026ba140 handle_events() + 176
13  BoE Scenario Editor           	       0x1026b9e58 main + 352
14  dyld                          	       0x1846d8274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	       0x184a530e8 start_wqthread + 0

Thread 11:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x184a16ed0 semaphore_wait_trap + 8
1   caulk                         	       0x18fb83ff4 caulk::semaphore::timed_wait(double) + 220
2   caulk                         	       0x18fb83ea0 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x18fb83b74 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x184a582e4 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x184a530fc thread_start + 8

Thread 12:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	       0x184a16ed0 semaphore_wait_trap + 8
1   caulk                         	       0x18fb83ff4 caulk::semaphore::timed_wait(double) + 220
2   caulk                         	       0x18fb83ea0 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x18fb83b74 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x184a582e4 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x184a530fc thread_start + 8

Thread 13:: caulk::deferred_logger
0   libsystem_kernel.dylib        	       0x184a16ed0 semaphore_wait_trap + 8
1   caulk                         	       0x18fb83ff4 caulk::semaphore::timed_wait(double) + 220
2   caulk                         	       0x18fb83ea0 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x18fb83b74 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x184a582e4 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x184a530fc thread_start + 8

Thread 14:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x184a16edc semaphore_wait_signal_trap + 8
1   caulk                         	       0x18fba05c4 caulk::mach::semaphore::wait_signal_or_error(caulk::mach::semaphore&) + 36
2   CoreAudio                     	       0x187594330 HALC_ProxyIOContext::IOWorkLoop() + 4892
3   CoreAudio                     	       0x187592898 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 176
4   CoreAudio                     	       0x187743760 HALC_IOThread::Entry(void*) + 88
5   libsystem_pthread.dylib       	       0x184a582e4 _pthread_start + 136
6   libsystem_pthread.dylib       	       0x184a530fc thread_start + 8

Thread 15:
0   libsystem_kernel.dylib        	       0x184a16ed0 semaphore_wait_trap + 8
1   libdispatch.dylib             	       0x1848a5b50 _dispatch_sema4_wait + 28
2   libdispatch.dylib             	       0x1848a6204 _dispatch_semaphore_wait_slow + 132
3   OpenAL                        	       0x10427e3ac alsem_wait + 20
4   OpenAL                        	       0x10424b018 EventThread + 240
5   OpenAL                        	       0x10427e194 althrd_starter + 28
6   libsystem_pthread.dylib       	       0x184a582e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x184a530fc thread_start + 8

Thread 16:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x184a16f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x184a29604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x184a1faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x184a1729c mach_msg + 24
4   CoreFoundation                	       0x184b40a4c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x184b3f2ac __CFRunLoopRun + 1212
6   CoreFoundation                	       0x184b3e734 CFRunLoopRunSpecific + 588
7   AppKit                        	       0x1887db278 _NSEventThread + 148
8   libsystem_pthread.dylib       	       0x184a582e4 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x184a530fc thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000090   x1: 0x0000000000000090   x2: 0x0000000000000000   x3: 0x000000016d95324a
    x4: 0x000000016d953268   x5: 0x0000000000000020   x6: 0x0000000000000020   x7: 0x0000000000000276
    x8: 0x000000016d9531f8   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000001
   x12: 0x0000000000000001  x13: 0x000000016d952b57  x14: 0x000000009842283a  x15: 0x0000000098222039
   x16: 0x0000000102b748a8  x17: 0xd08c00016d9531f8  x18: 0x0000000000000000  x19: 0x00000001ee12c050
   x20: 0x00000001ee12c0a0  x21: 0x00000001ee12c050  x22: 0x000000016d953918  x23: 0x000000016d953918
   x24: 0x00000001846d2000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016d952ec0   lr: 0x00000001024ed050
    sp: 0x000000016d952eb0   pc: 0x00000001024ed050 cpsr: 0x20001000
   far: 0x00000000000000a7  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1024ac000 -        0x102b67fff com.spidweb.boesceneditor (*) <5f8a617e-e1ad-305e-842e-d07720a3725d> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/MacOS/BoE Scenario Editor
       0x103d6c000 -        0x103d6ffff libboost_system.dylib (*) <1ff9f92e-b1df-32b1-803f-29c9a74313cf> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libboost_system.dylib
       0x103dd4000 -        0x103debfff libboost_filesystem.dylib (*) <c1178575-73ac-39f4-a70b-2c2b2671cca8> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libboost_filesystem.dylib
       0x103dac000 -        0x103db3fff libsfml-system.2.6.dylib (*) <c1c822db-7539-38a9-9fb4-9470cab23a46> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libsfml-system.2.6.dylib
       0x103e8c000 -        0x103eb3fff libsfml-window.2.6.dylib (*) <8cd12668-b9ca-389a-9902-25ce38276fd6> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libsfml-window.2.6.dylib
       0x103d74000 -        0x103d93fff libsfml-audio.2.6.dylib (*) <97269d57-6066-3b83-9dea-4ecc0a16b362> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libsfml-audio.2.6.dylib
       0x103ed4000 -        0x103f33fff libsfml-graphics.2.6.dylib (*) <2ec23e70-b2de-36da-8017-3a356fc20558> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libsfml-graphics.2.6.dylib
       0x103e34000 -        0x103e37fff libboost_atomic.dylib (*) <1f4d9830-d681-3414-a1f0-46b815751776> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/libboost_atomic.dylib
       0x104238000 -        0x1042f3fff org.sfml-dev.OpenAL (*) <e78e2127-8590-3090-ab9b-1b467f7ed42a> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/OpenAL.framework/Versions/A/OpenAL
       0x10432c000 -        0x1043a3fff org.sfml-dev.vorbisenc (*) <ca8fe886-3f9e-3ad1-aaef-118efc3714ea> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/vorbisenc.framework/Versions/A/vorbisenc
       0x103d58000 -        0x103d5ffff org.sfml-dev.vorbisfile (*) <01df2012-259d-3c48-8b6b-9b63e9a0e873> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/vorbisfile.framework/Versions/A/vorbisfile
       0x103e4c000 -        0x103e77fff org.sfml-dev.vorbis (*) <c6118866-b081-3fa5-9973-d18649dce10c> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/vorbis.framework/Versions/A/vorbis
       0x103dc4000 -        0x103dc7fff org.sfml-dev.ogg (*) <ee750711-3fe3-3b1a-ad5c-9e722b882575> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/ogg.framework/Versions/A/ogg
       0x10404c000 -        0x104073fff org.sfml-dev.FLAC (*) <672ef016-5023-323d-8078-2272c2a44264> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/FLAC.framework/Versions/A/FLAC
       0x104088000 -        0x10413ffff org.sfml-dev.freetype (*) <9259a232-a732-338f-af89-669f7bc94af3> /Users/USER/Desktop/*/BoE Scenario Editor.app/Contents/Frameworks/freetype.framework/Versions/A/freetype
       0x1074fc000 -        0x107563fff com.apple.AppleMetalOpenGLRenderer (1.0) <a969aeaf-d20c-3296-b195-742e2b280d5e> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
       0x107594000 -        0x107c37fff com.apple.AGXMetalG13X (324.6) <d03677d4-c896-3fd7-88c0-abed05133e06> /System/Library/Extensions/AGXMetalG13X.bundle/Contents/MacOS/AGXMetalG13X
       0x107fbc000 -        0x107fc7fff libobjc-trampolines.dylib (*) <3d687e9b-e092-3632-bc1d-74b19d492de0> /usr/lib/libobjc-trampolines.dylib
       0x117490000 -        0x1175cbfff com.apple.audio.units.Components (1.14) <ce006ced-ee1c-3174-bba9-1e326231ab55> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x1846d2000 -        0x184753f3f dyld (*) <398a133c-9bcb-317f-a064-a40d3cea3c0f> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x184a51000 -        0x184a5dfff libsystem_pthread.dylib (*) <642faf7a-874e-37e6-8aba-2b0cc09a3025> /usr/lib/system/libsystem_pthread.dylib
       0x184a16000 -        0x184a50ff7 libsystem_kernel.dylib (*) <eee9d0d3-dffc-37cb-9ced-b27cd0286d8c> /usr/lib/system/libsystem_kernel.dylib
       0x18fb82000 -        0x18fba9fff com.apple.audio.caulk (1.0) <a307ba82-97de-37d1-99b7-bf68ac23c35c> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x1873a2000 -        0x187aedfff com.apple.audio.CoreAudio (5.0) <214b90dc-87e8-30a8-b682-c2c1883f9635> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
       0x1848a1000 -        0x1848e7fff libdispatch.dylib (*) <5576e4fd-aad2-3608-8c8f-4eec421236f9> /usr/lib/system/libdispatch.dylib
       0x184ac3000 -        0x184fb7fff com.apple.CoreFoundation (6.9) <190e6a36-fcaa-3ea3-94bb-7009c44653da> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x18867b000 -        0x189ab7fff com.apple.AppKit (6.9) <b88a44c1-d617-33dc-90ed-b6ab417c428e> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)
Writable regions: Total=1.7G written=819K(0%) resident=819K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG image                           144K        8 
ColorSync                          624K       31 
CoreAnimation                     4832K       53 
CoreGraphics                        64K        4 
CoreUI image data                  752K       10 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.6G       69 
MALLOC guard page                  288K       18 
OpenGL GLSL                        256K        3 
STACK GUARD                       56.3M       17 
Stack                             18.0M       17 
VM_ALLOCATE                        464K       17 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__AUTH                            5130K      655 
__AUTH_CONST                      69.7M      897 
__CTF                               824        1 
__DATA                            24.5M      898 
__DATA_CONST                      24.1M      922 
__DATA_DIRTY                      2755K      334 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       626.9M       20 
__OBJC_RW                         2374K        1 
__TEXT                             1.0G      943 
__TPRO_CONST                       272K        2 
dyld private memory                 48K        2 
mapped file                      229.9M       29 
owned unmapped memory             4384K        1 
page table in kernel               819K        1 
shared memory                     1600K       23 
===========                     =======  ======= 
TOTAL                              3.7G     4985 
TOTAL, minus reserved VM space     3.7G     4985 

-----------
Full Report
-----------

{"app_name":"BoE Scenario Editor","timestamp":"2025-05-23 21:52:53.00 +0200","app_version":"","slice_uuid":"5f8a617e-e1ad-305e-842e-d07720a3725d","build_version":"1.0","platform":1,"bundleID":"com.spidweb.boesceneditor","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.3.1 (24D70)","roots_installed":0,"name":"BoE Scenario Editor","incident_id":"D692C21B-AC2C-4378-957C-EAD546CEC4C8"}
{
  "uptime" : 130000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "coalitionID" : 21401,
  "osVersion" : {
    "train" : "macOS 15.3.1",
    "build" : "24D70",
    "releaseType" : "User"
  },
  "captureTime" : "2025-05-23 21:52:53.1858 +0200",
  "codeSigningMonitor" : 1,
  "incident" : "D692C21B-AC2C-4378-957C-EAD546CEC4C8",
  "pid" : 27482,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2025-05-23 21:52:45.1588 +0200",
  "procStartAbsTime" : 3197850974713,
  "procExitAbsTime" : 3198043223164,
  "procName" : "BoE Scenario Editor",
  "procPath" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/MacOS\/BoE Scenario Editor",
  "bundleInfo" : {"CFBundleVersion":"1.0","CFBundleIdentifier":"com.spidweb.boesceneditor"},
  "storeInfo" : {"deviceIdentifierForVendor":"A44595BB-E80A-514D-86A0-83B16A411585","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.spidweb.boesceneditor",
  "crashReporterKey" : "31A2DAB3-D64B-CB2D-70A3-0F6A5FA40472",
  "codeSigningID" : "BoE Scenario Editor",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570556929,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"4AdA+f17Qqn\/wwCRwANf1v+DANH9ewGp\/UMAkeAHAPngB0D5IAAAlA==","atPC":"CFxAOQh9B1MIHQBy6AefGgABABL9e0Gp\/4MAkcADX9b\/gwDR\/XsBqQ=="},
  "bootSessionUUID" : "7FA300BF-A151-4F4B-9AC6-D70C88198EF4",
  "wakeTime" : 46976,
  "sleepWakeUUID" : "E9AB18A3-2790-450B-B025-572E897EF705",
  "sip" : "enabled",
  "vmRegionInfo" : "0xa7 is not in any region.  Bytes before following region: 4333420377\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1024ac000-102b68000    [ 6896K] r-x\/r-x SM=COW  \/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/MacOS\/BoE Scenario Editor",
  "exception" : {"codes":"0x0000000000000001, 0x00000000000000a7","rawCodes":[1,167],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000000000a7"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":27482},
  "vmregioninfo" : "0xa7 is not in any region.  Bytes before following region: 4333420377\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1024ac000-102b68000    [ 6896K] r-x\/r-x SM=COW  \/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/MacOS\/BoE Scenario Editor",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2828476,"threadState":{"x":[{"value":144},{"value":144},{"value":0},{"value":6133461578},{"value":6133461608},{"value":32},{"value":32},{"value":630},{"value":6133461496},{"value":0},{"value":0},{"value":1},{"value":1},{"value":6133459799},{"value":2554472506},{"value":2552373305},{"value":4340533416,"symbolLocation":24,"symbol":"vtable for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char>>"},{"value":15027386062761964024},{"value":0},{"value":8289173584,"symbolLocation":0,"symbol":"dyld4::preallocator"},{"value":8289173664,"symbolLocation":80,"symbol":"dyld4::preallocator"},{"value":8289173584,"symbolLocation":0,"symbol":"dyld4::preallocator"},{"value":6133463320},{"value":6133463320},{"value":6516711424},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4333686864},"cpsr":{"value":536875008},"fp":{"value":6133460672},"sp":{"value":6133460656},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4333686864,"matchesCrashFrame":1},"far":{"value":167}},"queue":"com.apple.main-thread","frames":[{"imageOffset":266320,"symbol":"std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:ue170006]() const","symbolLocation":24,"imageIndex":0},{"imageOffset":269920,"symbol":"std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__get_pointer[abi:ue170006]() const","symbolLocation":28,"imageIndex":0},{"imageOffset":269552,"symbol":"std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::data[abi:ue170006]() const","symbolLocation":24,"imageIndex":0},{"imageOffset":86580,"symbol":"std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::operator<<[abi:ue170006]<char, std::__1::char_traits<char>, std::__1::allocator<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)","symbolLocation":36,"imageIndex":0},{"imageOffset":85116,"symbol":"set_up_main_screen()","symbolLocation":1276,"imageIndex":0},{"imageOffset":2575716,"symbol":"set_current_out(location, bool, bool)","symbolLocation":184,"imageIndex":0},{"imageOffset":102504,"symbol":"restore_editor_state(bool)","symbolLocation":88,"imageIndex":0},{"imageOffset":60648,"symbol":"handle_lb_action(int)","symbolLocation":608,"imageIndex":0},{"imageOffset":20252,"symbol":"handle_lb_click(location)","symbolLocation":156,"imageIndex":0},{"imageOffset":19524,"symbol":"handle_action(location, sf::Event)","symbolLocation":236,"imageIndex":0},{"imageOffset":2166052,"symbol":"Mouse_Pressed(sf::Event const&)","symbolLocation":112,"imageIndex":0},{"imageOffset":2165248,"symbol":"handle_one_event(sf::Event const&)","symbolLocation":308,"imageIndex":0},{"imageOffset":2154816,"symbol":"handle_events()","symbolLocation":176,"imageIndex":0},{"imageOffset":2154072,"symbol":"main","symbolLocation":352,"imageIndex":0},{"imageOffset":25204,"symbol":"start","symbolLocation":2840,"imageIndex":19}]},{"id":2828481,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6134018048},{"value":5123},{"value":6133481472},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6134018048},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828483,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6134591488},{"value":6659},{"value":6134054912},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6134591488},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828486,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6135164928},{"value":21507},{"value":6134628352},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6135164928},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828494,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6135738368},{"value":40963},{"value":6135201792},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6135738368},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828495,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6136311808},{"value":34587},{"value":6135775232},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6136311808},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828496,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6136885248},{"value":35075},{"value":6136348672},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6136885248},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828497,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6137458688},{"value":40707},{"value":6136922112},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6137458688},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828498,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6138032128},{"value":34819},{"value":6137495552},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6138032128},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828499,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6138605568},{"value":35331},{"value":6138068992},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6138605568},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828500,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":21}],"threadState":{"x":[{"value":6139179008},{"value":174403},{"value":6138642432},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6139179008},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520385768},"far":{"value":0}}},{"id":2828592,"name":"caulk.messenger.shared:17","threadState":{"x":[{"value":14},{"value":105553180978810},{"value":0},{"value":6139752554},{"value":105553180978784},{"value":25},{"value":0},{"value":0},{"value":0},{"value":4294967295},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":18446744073709551580},{"value":8432678632},{"value":0},{"value":105553123564064},{"value":105553123564064},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6706184180},"cpsr":{"value":2147487744},"fp":{"value":6139752320},"sp":{"value":6139752288},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520139472},"far":{"value":0}},"frames":[{"imageOffset":3792,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":22},{"imageOffset":8180,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":220,"imageIndex":23},{"imageOffset":7840,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":23},{"imageOffset":7028,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":96,"imageIndex":23},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":21},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":21}]},{"id":2828593,"name":"caulk.messenger.shared:high","threadState":{"x":[{"value":14},{"value":64515},{"value":64515},{"value":15},{"value":4294967295},{"value":0},{"value":0},{"value":0},{"value":0},{"value":4294967295},{"value":1},{"value":105553170503880},{"value":0},{"value":0},{"value":0},{"value":0},{"value":18446744073709551580},{"value":8432678632},{"value":0},{"value":105553123564272},{"value":105553123564272},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6706184180},"cpsr":{"value":2147487744},"fp":{"value":6140325760},"sp":{"value":6140325728},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520139472},"far":{"value":0}},"frames":[{"imageOffset":3792,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":22},{"imageOffset":8180,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":220,"imageIndex":23},{"imageOffset":7840,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":23},{"imageOffset":7028,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":96,"imageIndex":23},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":21},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":21}]},{"id":2828594,"name":"caulk::deferred_logger","threadState":{"x":[{"value":14},{"value":105553143489463},{"value":0},{"value":6140899431},{"value":105553143489440},{"value":22},{"value":0},{"value":0},{"value":0},{"value":4294967295},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":18446744073709551580},{"value":8432678632},{"value":0},{"value":105553121501784},{"value":105553121501784},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6706184180},"cpsr":{"value":2147487744},"fp":{"value":6140899200},"sp":{"value":6140899168},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520139472},"far":{"value":0}},"frames":[{"imageOffset":3792,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":22},{"imageOffset":8180,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":220,"imageIndex":23},{"imageOffset":7840,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":23},{"imageOffset":7028,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":96,"imageIndex":23},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":21},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":21}]},{"id":2828595,"name":"com.apple.audio.IOThread.client","threadState":{"x":[{"value":14},{"value":88323},{"value":0},{"value":0},{"value":0},{"value":3414163456},{"value":4682792960},{"value":512},{"value":1},{"value":679058363425816785},{"value":1099511628032},{"value":1099511628034},{"value":4096},{"value":0},{"value":0},{"value":0},{"value":18446744073709551579},{"value":8432678640},{"value":0},{"value":5218080544},{"value":5218080536},{"value":0},{"value":105553180982048},{"value":5218080608},{"value":5218080272},{"value":5218080256},{"value":5218080616},{"value":512},{"value":5218079744}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6706300356},"cpsr":{"value":1610616832},"fp":{"value":6141472000},"sp":{"value":6141471984},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520139484},"far":{"value":0}},"frames":[{"imageOffset":3804,"symbol":"semaphore_wait_signal_trap","symbolLocation":8,"imageIndex":22},{"imageOffset":124356,"symbol":"caulk::mach::semaphore::wait_signal_or_error(caulk::mach::semaphore&)","symbolLocation":36,"imageIndex":23},{"imageOffset":2040624,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":4892,"imageIndex":24},{"imageOffset":2033816,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":176,"imageIndex":24},{"imageOffset":3807072,"symbol":"HALC_IOThread::Entry(void*)","symbolLocation":88,"imageIndex":24},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":21},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":21}]},{"id":2828612,"frames":[{"imageOffset":3792,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":22},{"imageOffset":19280,"symbol":"_dispatch_sema4_wait","symbolLocation":28,"imageIndex":25},{"imageOffset":20996,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":132,"imageIndex":25},{"imageOffset":287660,"symbol":"alsem_wait","symbolLocation":20,"imageIndex":8},{"imageOffset":77848,"symbol":"EventThread","symbolLocation":240,"imageIndex":8},{"imageOffset":287124,"symbol":"althrd_starter","symbolLocation":28,"imageIndex":8},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":21},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":21}],"threadState":{"x":[{"value":14},{"value":8589934595},{"value":171798697235},{"value":384841954624003},{"value":14680198217728},{"value":384841954623488},{"value":48},{"value":0},{"value":0},{"value":1},{"value":1023},{"value":2240},{"value":2043},{"value":2045},{"value":3180591245},{"value":3178492216},{"value":18446744073709551580},{"value":8432691872},{"value":0},{"value":105553148738304},{"value":105553148738240},{"value":18446744073709551615},{"value":4913798664},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6518627152},"cpsr":{"value":1610616832},"fp":{"value":6143617776},"sp":{"value":6143617760},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520139472},"far":{"value":0}}},{"id":2828620,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":394737559273472},{"value":0},{"value":394737559273472},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":2},{"value":0},{"value":0},{"value":0},{"value":91907},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8432672248},{"value":0},{"value":4294967295},{"value":2},{"value":394737559273472},{"value":0},{"value":394737559273472},{"value":6144188520},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6520215044},"cpsr":{"value":4096},"fp":{"value":6144188368},"sp":{"value":6144188288},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6520139604},"far":{"value":0}},"frames":[{"imageOffset":3924,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":22},{"imageOffset":79364,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":22},{"imageOffset":39672,"symbol":"mach_msg_overwrite","symbolLocation":480,"imageIndex":22},{"imageOffset":4764,"symbol":"mach_msg","symbolLocation":24,"imageIndex":22},{"imageOffset":514636,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":26},{"imageOffset":508588,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":26},{"imageOffset":505652,"symbol":"CFRunLoopRunSpecific","symbolLocation":588,"imageIndex":26},{"imageOffset":1442424,"symbol":"_NSEventThread","symbolLocation":148,"imageIndex":27},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":21},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":21}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4333420544,
    "CFBundleIdentifier" : "com.spidweb.boesceneditor",
    "size" : 7061504,
    "uuid" : "5f8a617e-e1ad-305e-842e-d07720a3725d",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/MacOS\/BoE Scenario Editor",
    "name" : "BoE Scenario Editor",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4359372800,
    "size" : 16384,
    "uuid" : "1ff9f92e-b1df-32b1-803f-29c9a74313cf",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libboost_system.dylib",
    "name" : "libboost_system.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4359798784,
    "size" : 98304,
    "uuid" : "c1178575-73ac-39f4-a70b-2c2b2671cca8",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libboost_filesystem.dylib",
    "name" : "libboost_filesystem.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4359634944,
    "size" : 32768,
    "uuid" : "c1c822db-7539-38a9-9fb4-9470cab23a46",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libsfml-system.2.6.dylib",
    "name" : "libsfml-system.2.6.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4360552448,
    "size" : 163840,
    "uuid" : "8cd12668-b9ca-389a-9902-25ce38276fd6",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libsfml-window.2.6.dylib",
    "name" : "libsfml-window.2.6.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4359405568,
    "size" : 131072,
    "uuid" : "97269d57-6066-3b83-9dea-4ecc0a16b362",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libsfml-audio.2.6.dylib",
    "name" : "libsfml-audio.2.6.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4360847360,
    "size" : 393216,
    "uuid" : "2ec23e70-b2de-36da-8017-3a356fc20558",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libsfml-graphics.2.6.dylib",
    "name" : "libsfml-graphics.2.6.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4360192000,
    "size" : 16384,
    "uuid" : "1f4d9830-d681-3414-a1f0-46b815751776",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/libboost_atomic.dylib",
    "name" : "libboost_atomic.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364402688,
    "CFBundleIdentifier" : "org.sfml-dev.OpenAL",
    "size" : 770048,
    "uuid" : "e78e2127-8590-3090-ab9b-1b467f7ed42a",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/OpenAL.framework\/Versions\/A\/OpenAL",
    "name" : "OpenAL",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4365402112,
    "CFBundleIdentifier" : "org.sfml-dev.vorbisenc",
    "size" : 491520,
    "uuid" : "ca8fe886-3f9e-3ad1-aaef-118efc3714ea",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/vorbisenc.framework\/Versions\/A\/vorbisenc",
    "name" : "vorbisenc",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4359290880,
    "CFBundleIdentifier" : "org.sfml-dev.vorbisfile",
    "size" : 32768,
    "uuid" : "01df2012-259d-3c48-8b6b-9b63e9a0e873",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/vorbisfile.framework\/Versions\/A\/vorbisfile",
    "name" : "vorbisfile",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4360290304,
    "CFBundleIdentifier" : "org.sfml-dev.vorbis",
    "size" : 180224,
    "uuid" : "c6118866-b081-3fa5-9973-d18649dce10c",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/vorbis.framework\/Versions\/A\/vorbis",
    "name" : "vorbis",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4359733248,
    "CFBundleIdentifier" : "org.sfml-dev.ogg",
    "size" : 16384,
    "uuid" : "ee750711-3fe3-3b1a-ad5c-9e722b882575",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/ogg.framework\/Versions\/A\/ogg",
    "name" : "ogg",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4362387456,
    "CFBundleIdentifier" : "org.sfml-dev.FLAC",
    "size" : 163840,
    "uuid" : "672ef016-5023-323d-8078-2272c2a44264",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/FLAC.framework\/Versions\/A\/FLAC",
    "name" : "FLAC",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4362633216,
    "CFBundleIdentifier" : "org.sfml-dev.freetype",
    "size" : 753664,
    "uuid" : "9259a232-a732-338f-af89-669f7bc94af3",
    "path" : "\/Users\/USER\/Desktop\/*\/BoE Scenario Editor.app\/Contents\/Frameworks\/freetype.framework\/Versions\/A\/freetype",
    "name" : "freetype",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4417634304,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.AppleMetalOpenGLRenderer",
    "size" : 425984,
    "uuid" : "a969aeaf-d20c-3296-b195-742e2b280d5e",
    "path" : "\/System\/Library\/Extensions\/AppleMetalOpenGLRenderer.bundle\/Contents\/MacOS\/AppleMetalOpenGLRenderer",
    "name" : "AppleMetalOpenGLRenderer",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4418256896,
    "CFBundleShortVersionString" : "324.6",
    "CFBundleIdentifier" : "com.apple.AGXMetalG13X",
    "size" : 6963200,
    "uuid" : "d03677d4-c896-3fd7-88c0-abed05133e06",
    "path" : "\/System\/Library\/Extensions\/AGXMetalG13X.bundle\/Contents\/MacOS\/AGXMetalG13X",
    "name" : "AGXMetalG13X",
    "CFBundleVersion" : "324.6"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4428906496,
    "size" : 49152,
    "uuid" : "3d687e9b-e092-3632-bc1d-74b19d492de0",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4685627392,
    "CFBundleShortVersionString" : "1.14",
    "CFBundleIdentifier" : "com.apple.audio.units.Components",
    "size" : 1294336,
    "uuid" : "ce006ced-ee1c-3174-bba9-1e326231ab55",
    "path" : "\/System\/Library\/Components\/CoreAudio.component\/Contents\/MacOS\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "1.14"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6516711424,
    "size" : 532288,
    "uuid" : "398a133c-9bcb-317f-a064-a40d3cea3c0f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6520377344,
    "size" : 53248,
    "uuid" : "642faf7a-874e-37e6-8aba-2b0cc09a3025",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6520135680,
    "size" : 241656,
    "uuid" : "eee9d0d3-dffc-37cb-9ced-b27cd0286d8c",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6706176000,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 163840,
    "uuid" : "a307ba82-97de-37d1-99b7-bf68ac23c35c",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6563700736,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7651328,
    "uuid" : "214b90dc-87e8-30a8-b682-c2c1883f9635",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6518607872,
    "size" : 290816,
    "uuid" : "5576e4fd-aad2-3608-8c8f-4eec421236f9",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6520844288,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5197824,
    "uuid" : "190e6a36-fcaa-3ea3-94bb-7009c44653da",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "3302.1.400"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6583463936,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 21221376,
    "uuid" : "b88a44c1-d617-33dc-90ed-b6ab417c428e",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2575.40.6"
  }
],
  "sharedCache" : {
  "base" : 6515900416,
  "size" : 4865835008,
  "uuid" : "d272b91e-f9f0-3854-b5b9-508b21c25dcc"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)\nWritable regions: Total=1.7G written=819K(0%) resident=819K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG image                           144K        8 \nColorSync                          624K       31 \nCoreAnimation                     4832K       53 \nCoreGraphics                        64K        4 \nCoreUI image data                  752K       10 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.6G       69 \nMALLOC guard page                  288K       18 \nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.3M       17 \nStack                             18.0M       17 \nVM_ALLOCATE                        464K       17 \nVM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)\n__AUTH                            5130K      655 \n__AUTH_CONST                      69.7M      897 \n__CTF                               824        1 \n__DATA                            24.5M      898 \n__DATA_CONST                      24.1M      922 \n__DATA_DIRTY                      2755K      334 \n__FONT_DATA                        2352        1 \n__GLSLBUILTINS                    5174K        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       626.9M       20 \n__OBJC_RW                         2374K        1 \n__TEXT                             1.0G      943 \n__TPRO_CONST                       272K        2 \ndyld private memory                 48K        2 \nmapped file                      229.9M       29 \nowned unmapped memory             4384K        1 \npage table in kernel               819K        1 \nshared memory                     1600K       23 \n===========                     =======  ======= \nTOTAL                              3.7G     4985 \nTOTAL, minus reserved VM space     3.7G     4985 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "a7de0fd6fe6d47e0d66d1b76aa88ee804915a954",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645eb1d0417dab722a215927",
      "factorPackIds" : {

      },
      "deploymentId" : 240000005
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [

  ]
}
}
</details>

### LINKED ISSUE #748: Can't see custom scenario in list if .exs file extension in name is not in lower caps
On Mac, if the scenario is called `scenario.EXS` instead of `scenario.exs`, it doesn't show up in the list

### PR DESCRIPTION
**Pull request by NQNStudios**
Fix #132
Fix #685
Fix #735
Fix #748 
Fix #744 
Fix #741 
Fix #740 
Fix #737 
Fix #736 
Fix #735 
Fix #733
Fix #729 
Fix #707
Fix #703

### CODE REVIEW

**Comment by NQNStudios** [comment]
Uh, I don't remember accidentally closing this? Weird. It is open.

**Comment by CelticMinstrel** [comment]
Re: 88bdce13a9a0d465f2403c0445be2976c06e1667

This looks like it _might_ be wrong. Does it mean that the party graphics sheet does not get cleared when you make a new party? I assume loading a party should be fine though.

Re: cfe8db4456c91065c255ea4f61ecf20ca5ab83fe

> if we make custom graphics allowed on PCs

They are already allowed, though the Create PC special node is required to make one. I think it would be fine to put a placeholder image for PCs with custom graphics though.

**Comment by NQNStudios** [comment]
>Re: https://github.com/calref/cboe/commit/88bdce13a9a0d465f2403c0445be2976c06e1667
>
>This looks like it might be wrong. Does it mean that the party graphics sheet does not get cleared when you make a new party? I assume loading a party should be fine though.

That happens in start_new_game() through a call of `	spec_scen_g.party_sheet.reset();`

**Comment by NQNStudios** [comment]
@CelticMinstrel I'm done adding to this one unless you have more changes to request.

**Comment by NQNStudios** [comment]
I spoke too soon, I might as well push fixes to newly found bugs in this PR as long as it's still open.

File: src/dialogxml/dialogs/dialog.cpp [hunk 1]
```diff
@@ -452,6 +445,12 @@ void cDialog::recalcRect(){
 
 	winRect.right *= get_ui_scale();
 	winRect.bottom *= get_ui_scale();
+	// Uncomment if you need to measure any dialogs.
+	/*
+	LOG_VALUE(fname);
+	LOG_VALUE(winRect.right);
+	LOG_VALUE(winRect.bottom);
+	*/
```
Comment (CelticMinstrel) [inline src/dialogxml/dialogs/dialog.cpp:453]:
```suggestion
	//*/
```

Comment (NQNStudios) [reply src/dialogxml/dialogs/dialog.cpp:453]: Is this a clever way to make it so the first `/*` can be removed without changing another line? Cool.

**Comment by CelticMinstrel** [comment]
Re: 4620074e91e53c91652d54236ff7a1bc8d162e14

That doesn't look right. Why not just use the string picker with STRT_ITEM?

**Comment by NQNStudios** [comment]
You're right, that will be better.

Before I go putting get_num_response back where it was, is there any reason we might want to keep it available to scenedit or pcedit? Or any reason not to?

**Comment by CelticMinstrel** [comment]
> Before I go putting get_num_response back where it was, is there any reason we might want to keep it available to scenedit or pcedit? Or any reason not to?

Hmm. I can't think of any reason we'd want to actually get a numeric response in the editor – pretty much all such cases would drop an input field right into the dialog. It would make sense to use the `get_num_response` dialog in the special node preview system, but… I don't think that would use the same function?

Re: e5f4663212e5ae164efd49dab167483fb1b743fa

That's technically fine (I think) but not quite what I meant. There's a function that takes a cStrChoice parameter, and you can pass STRT_ITEM to choose an item.

**Comment by CelticMinstrel** [comment]
Re: d8d53b8528ce414cd042434f27f710c5295f8446

That's a good idea, but why not go even further? Instead of a left button, just automatically load the last scenario at launch. You could maybe have a preference to disable it, not sure if that's needed.

**Comment by NQNStudios** [comment]
> That's a good idea, but why not go even further? 

They wouldn't get the chance to click New Scenario. But *most* of the time they'll want to load the last one if there is one -- so maybe we could do that.

**Comment by CelticMinstrel** [comment]
Well, that was _not_ an expected use-case for the location picker, but I guess it's not a bad idea.

Re: 50a440e4e3695f2015cc8b0e79b0aaaf2eda0d37

Did you verify that this doesn't create any situation where:

1. You change one of those properties.
2. You do other stuff which causes them to be stored.
3. You click cancel.
4. The properties are stil changed if you look at the item again.

It should be fine as long as the item you're editing is not a direct reference to an item in the scenario… I don't remember whether it is…

**Comment by NQNStudios** [comment]
The dialog stores and modifies a copy of the item, then only when OK is pressed does it overwrite the real item in the town object.

**Comment by NQNStudios** [comment]
It could be the case that it wouldn't save it out. What I tested was putting blank title/whitespace-only title in the New Scenario field, then checking Scenario Details to see if it had been trimmed. I didn't save.
